[2024-06-18T12:00:12.310+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-18T11:53:44.483158+00:00 [queued]>
[2024-06-18T12:00:12.316+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-18T11:53:44.483158+00:00 [queued]>
[2024-06-18T12:00:12.317+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-06-18T12:00:12.324+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2024-06-18 11:53:44.483158+00:00
[2024-06-18T12:00:12.329+0000] {standard_task_runner.py:57} INFO - Started process 18334 to run task
[2024-06-18T12:00:12.333+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'scheduled__2024-06-18T11:53:44.483158+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpr9a28r0r']
[2024-06-18T12:00:12.334+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask kafka_data_stream
[2024-06-18T12:00:12.392+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream scheduled__2024-06-18T11:53:44.483158+00:00 [running]> on host 2ad9230613d5
[2024-06-18T12:00:12.437+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:53:44.483158+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T11:53:44.483158+00:00'
[2024-06-18T12:00:12.441+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-06-18T12:00:12.441+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-06-18T12:00:12.442+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Connection complete.
[2024-06-18T12:00:12.548+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-06-18T12:00:12.548+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-06-18T12:00:12.550+0000] {logging_mixin.py:154} INFO - {'baseurl': 'https://fantasy.premierleague.com/api', 'endpoints': [{'name': 'bootstrap-static', 'tables': ['elements', 'teams']}, {'name': 'fixtures'}]}
[2024-06-18T12:00:13.111+0000] {conn.py:380} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: connecting to kafka:9092 [('172.18.0.3', 9092) IPv4]
[2024-06-18T12:00:13.112+0000] {conn.py:410} INFO - <BrokerConnection node_id=0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.3', 9092)]>: Connection complete.
[2024-06-18T12:00:13.112+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.3', 9092)]>: Closing connection. 
[2024-06-18T12:01:13.062+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/kafka_client/kafka_stream_data.py", line 154, in stream
    producer.send('{key}', json.dumps(data).encode("utf-8"))
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 576, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 702, in _wait_on_metadata
    raise Errors.KafkaTimeoutError(
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-06-18T12:01:13.094+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20240618T115344, start_date=20240618T120012, end_date=20240618T120113
[2024-06-18T12:01:13.118+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task kafka_data_stream (KafkaTimeoutError: Failed to update metadata after 60.0 secs.; 18334)
[2024-06-18T12:01:13.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-18T12:01:13.173+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
