[2024-06-21T12:19:34.167+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:21:43.743487+00:00 [queued]>
[2024-06-21T12:19:34.172+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:21:43.743487+00:00 [queued]>
[2024-06-21T12:19:34.172+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-06-21T12:19:34.181+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2024-06-20 15:21:43.743487+00:00
[2024-06-21T12:19:34.186+0000] {standard_task_runner.py:57} INFO - Started process 28943 to run task
[2024-06-21T12:19:34.189+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'scheduled__2024-06-20T15:21:43.743487+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpl3rjqb8r']
[2024-06-21T12:19:34.193+0000] {standard_task_runner.py:85} INFO - Job 248: Subtask pyspark_consumer
[2024-06-21T12:19:34.216+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 248 for task pyspark_consumer (DagRun for kafka_spark_dag with run_id or execution_date of 'scheduled__2024-06-20T15:21:43.743487+00:00' not found; 28943)
[2024-06-21T12:19:34.223+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-21T12:19:34.235+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T12:19:36.424+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:21:43.743487+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-06-21T12:19:36.425+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:21:43.743487+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-06-21T12:19:36.428+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
