[2024-06-21T12:19:34.167+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:23:46.003430+00:00 [queued]>
[2024-06-21T12:19:34.172+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer scheduled__2024-06-20T15:23:46.003430+00:00 [queued]>
[2024-06-21T12:19:34.172+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-06-21T12:19:34.182+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2024-06-20 15:23:46.003430+00:00
[2024-06-21T12:19:34.186+0000] {standard_task_runner.py:57} INFO - Started process 28944 to run task
[2024-06-21T12:19:34.191+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'scheduled__2024-06-20T15:23:46.003430+00:00', '--job-id', '1958', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpoyd92czw']
[2024-06-21T12:19:34.194+0000] {standard_task_runner.py:85} INFO - Job 1958: Subtask pyspark_consumer
[2024-06-21T12:19:34.216+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1958 for task pyspark_consumer (DagRun for kafka_spark_dag with run_id or execution_date of 'scheduled__2024-06-20T15:23:46.003430+00:00' not found; 28944)
[2024-06-21T12:19:34.223+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-21T12:19:34.236+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
